# FTP login informations
ftp:
  host: "ftp.address.tld"
  port: 21
  user: "username"
  password: "mypassword"  # let empty to prompt at executing

# if strict is true, the program will delete remote files/directories that are not in local
strict: true
# if confirm_delete is true, the program will ask confirm before delete a file/directory
confirm_delete: true
filter: "*"

# directories to synchronize !
directories:
  - # dir1
    local:          '/path/to/dir1'
    remote:         '/remote/path/to/dir1'
    ignore:         ['/directo_to_ignore', '/file_to_ignore.php', '/otherdir/*', '*.gif', '/dir42/*.png']
    remote_ignore:  ['.htaccess']
  - # dir2
    local:          '/path/to/dir2'
    remote:         '/remote/path/to/dir2'
    ignore:         []
    remote_ignore:  []

# DIR FTP command result line parser
dir_ftp_line_parser:
  format:           "%(permissions)s\\s+%(inode)s\\s+%(user)s\\s+%(group)s\\s+%(size)s\\s+%(month)s\\s+%(day)s\\s+(?:%(time)s|%(year)s)\\s+%(filename)s"
  fields:
    permissions : '(?P<permissions>(?:d|s|-)(?:r|-)(?:w|-)(?:x|-)(?:r|-)(?:w|-)(?:x|s|-)(?:r|-)(?:w|-)(?:x|-))'
    inode       : '(?P<inode>[0-9]+)'
    user        : '(?P<user>[a-zA-Z0-9\-_]+)'
    group       : '(?P<group>[a-zA-Z0-9\-_]+)'
    size        : '(?P<size>[0-9]+)'
    month       : '(?P<month>[a-zA-Z]{3})'
    day         : '(?P<day>[0-9]+)'
    time        : '(?P<hour>[0-9]{2}):(?P<minute>[0-9]{2})'
    year         : '(?P<year>[0-9]{4})'
    filename    : '(?P<filename>.*)'